SELECT
  CASE 
    WHEN REVIEW_COUNT > 50 THEN 'VERY_POPULAR'
    WHEN REVIEW_COUNT BETWEEN 20 AND 50 THEN 'MED_POPULAR'
    ELSE 'LOW_POPULAR'
  END AS POP_GROUP,
  IS_OPEN,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY POP_GROUP), 2) AS PERCENTAGE
FROM STG_YELP_BUSINESS
GROUP BY POP_GROUP, IS_OPEN
ORDER BY POP_GROUP, IS_OPEN;


CREATE OR REPLACE TABLE ANALYTICS_RESTAURANT_SIGNAL_IMPORTANCE AS
SELECT
  M.BUSINESS_ID,
  M.YEAR_MONTH,
  M.AVG_RATING,
  M.RATING_VOLATILITY,
  M.REVIEWS_COUNT,
  C.CHECKINS_COUNT,
  LAG(M.REVIEWS_COUNT,1) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS REVIEWS_LAST_MONTH,
  LAG(C.CHECKINS_COUNT,1) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS CHECKINS_LAST_MONTH,
  ROUND(M.REVIEWS_COUNT - REVIEWS_LAST_MONTH,2) AS REVIEWS_CHANGE_1M,
  ROUND(C.CHECKINS_COUNT - CHECKINS_LAST_MONTH,2) AS CHECKINS_CHANGE_1M
FROM ANALYTICS_RESTAURANT_MONTHLY M
JOIN ANALYTICS_RESTAURANT_CHECKINS_MONTHLY C
  ON M.BUSINESS_ID = C.BUSINESS_ID
 AND M.YEAR_MONTH = C.YEAR_MONTH
ORDER BY M.BUSINESS_ID, M.YEAR_MONTH;

CREATE OR REPLACE TABLE ANALYTICS_SENTIMENT_MONTHLY AS
SELECT
  BUSINESS_ID,
  TO_CHAR(DATE_TRUNC('MONTH', REVIEW_DATE), 'YYYY-MM') AS YEAR_MONTH,
  COUNT(*) AS TOTAL_REVIEWS,
  SUM(CASE WHEN SENTIMENTS = 'NEGATIVE' THEN 1 ELSE 0 END) AS NEG_REVIEWS,
  SUM(CASE WHEN SENTIMENTS = 'POSITIVE' THEN 1 ELSE 0 END) AS POS_REVIEWS,
  ROUND(NEG_REVIEWS / TOTAL_REVIEWS, 3) AS NEG_SENTIMENT_RATIO,
  ROUND(POS_REVIEWS / TOTAL_REVIEWS, 3) AS POS_SENTIMENT_RATIO
FROM STG_YELP_REVIEWS
GROUP BY 1,2
ORDER BY 1,2;

CREATE OR REPLACE TABLE ANALYTICS_ENGAGEMENT_LIFT_BASE AS
SELECT
  M.BUSINESS_ID,
  M.YEAR_MONTH,
  M.REVIEWS_COUNT,
  C.CHECKINS_COUNT,
  B.OPENED,
  LAG(M.REVIEWS_COUNT,1) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS REVIEWS_LAST_MONTH,
  LAG(C.CHECKINS_COUNT,1) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS CHECKINS_LAST_MONTH,
  ROUND(((M.REVIEWS_COUNT - REVIEWS_LAST_MONTH) / NULLIF(REVIEWS_LAST_MONTH,0)) * 100, 2) AS REVIEW_VELOCITY_DROP_PERCENT,
  ROUND(((C.CHECKINS_COUNT - CHECKINS_LAST_MONTH) / NULLIF(CHECKINS_LAST_MONTH,0)) * 100, 2) AS CHECKIN_VELOCITY_DROP_PERCENT
FROM ANALYTICS_RESTAURANT_MONTHLY M
JOIN ANALYTICS_RESTAURANT_CHECKINS_MONTHLY C
  ON M.BUSINESS_ID = C.BUSINESS_ID
 AND M.YEAR_MONTH = C.YEAR_MONTH
JOIN STG_YELP_BUSINESS B
  ON M.BUSINESS_ID = B.BUSINESS_ID
ORDER BY M.BUSINESS_ID, M.YEAR_MONTH;

CREATE OR REPLACE TABLE ANALYTICS_COMPOSITE_RISK_2 AS
SELECT
  BUSINESS_ID,
  YEAR_MONTH,
  OPENED,
  REVIEW_VELOCITY_DROP_PERCENT,
  CHECKIN_VELOCITY_DROP_PERCENT,
  NEG_SENTIMENT_RATIO,
  RATING_VOLATILITY,
  REVIEWS_COUNT,
  CHECKINS_COUNT,
  ROUND(
      (NEG_SENTIMENT_RATIO * 3) +
      (REVIEW_VELOCITY_DROP_PERCENT * -0.02) +
      (CHECKIN_VELOCITY_DROP_PERCENT * -0.015) +
      (RATING_VOLATILITY * 1.5)
  , 3) AS RISK_SCORE_2
FROM ANALYTICS_ENGAGEMENT_LIFT_BASE E
JOIN ANALYTICS_SENTIMENT_MONTHLY S
  ON E.BUSINESS_ID = S.BUSINESS_ID
 AND E.YEAR_MONTH = S.YEAR_MONTH
ORDER BY BUSINESS_ID, YEAR_MONTH;

CREATE OR REPLACE TABLE ANALYTICS_BUSINESS_FAILURE AS
SELECT
  BUSINESS_ID,
  MAX(IS_OPEN) AS EVER_OPENED,
  MIN(IS_OPEN) AS EVER_CLOSED,
  COUNT(*) AS MONTHS_OBSERVED,
  SUM(CASE WHEN IS_OPEN = 0 THEN 1 ELSE 0 END) AS CLOSED_MONTHS,
  CASE 
    WHEN EVER_OPENED = 1 AND EVER_CLOSED = 0 AND CLOSED_MONTHS >= 6 
    THEN 1 ELSE 0 END AS FAILED_FLAG
FROM STG_YELP_BUSINESS
GROUP BY BUSINESS_ID;

CREATE OR REPLACE TABLE ANALYTICS_TARGET_STRESS AS
SELECT
  BUSINESS_ID,
  YEAR_MONTH,
  AVG_RATING,
  RATING_CHANGE_3M,
  CASE WHEN RATING_CHANGE_3M < -0.4 THEN 1 ELSE 0 END AS RATING_STRESS_FLAG
FROM ANALYTICS_RESTAURANT_RATING_TREND;


SELECT RATING_STRESS_FLAG, COUNT(*) FROM ANALYTICS_TARGET_STRESS GROUP BY 1;


CCREATE OR REPLACE TABLE ANALYTICS_RISK_SIGNALS_NORMALIZED AS
WITH BASE AS (
  SELECT
    M.BUSINESS_ID,
    M.YEAR_MONTH,
    M.REVIEWS_COUNT,
    C.CHECKINS_COUNT,
    M.AVG_RATING,
    M.RATING_VOLATILITY,
    S.NEG_SENTIMENT_RATIO,
    B.IS_OPEN,
    LAG(M.REVIEWS_COUNT) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS REVIEWS_LAST_MONTH,
    LAG(C.CHECKINS_COUNT) OVER (PARTITION BY M.BUSINESS_ID ORDER BY TO_DATE(M.YEAR_MONTH||'-01')) AS CHECKINS_LAST_MONTH
  FROM ANALYTICS_RESTAURANT_MONTHLY M
  JOIN STG_YELP_BUSINESS B
    ON M.BUSINESS_ID = B.BUSINESS_ID
  JOIN ANALYTICS_SENTIMENT_MONTHLY S
    ON M.BUSINESS_ID = S.BUSINESS_ID
   AND M.YEAR_MONTH = S.YEAR_MONTH
  JOIN ANALYTICS_RESTAURANT_CHECKINS_MONTHLY C
    ON M.BUSINESS_ID = C.BUSINESS_ID
   AND M.YEAR_MONTH = C.YEAR_MONTH
),
NORMALIZED AS (
  SELECT *,
    ROUND((REVIEWS_COUNT - COALESCE(REVIEWS_LAST_MONTH,0)) / NULLIF(COALESCE(REVIEWS_LAST_MONTH,1),0),3) AS REVIEWS_VELOCITY,
    ROUND((CHECKINS_COUNT - COALESCE(CHECKINS_LAST_MONTH,0)) / NULLIF(COALESCE(CHECKINS_LAST_MONTH,1),0),3) AS CHECKINS_VELOCITY
  FROM BASE
)
SELECT
  BUSINESS_ID,
  YEAR_MONTH,
  AVG_RATING,
  REVIEW_COUNT AS TOTAL_USER_REVIEWS,
  REVIEWS_COUNT,
  CHECKINS_COUNT,
  RATING_VOLATILITY,
  NEG_SENTIMENT_RATIO,
  IS_OPEN,
  REVIEWS_VELOCITY,
  CHECKINS_VELOCITY,
  CASE WHEN REVIEWS_VELOCITY < -0.30 THEN 1 ELSE 0 END AS REVIEWS_SHARP_DROP,
  CASE WHEN CHECKINS_VELOCITY < -0.30 THEN 1 ELSE 0 END AS CHECKINS_SHARP_DROP,
  CASE WHEN NEG_SENTIMENT_RATIO > 0.30 THEN 1 ELSE 0 END AS NEGATIVE_SURGE,
  ROUND(
      (REVIEWS_SHARP_DROP * 2.5) +
      (CHECKINS_SHARP_DROP * 2.0) +
      (NEGATIVE_SURGE * 3.5) +
      (RATING_VOLATILITY * 1.8)
  , 3) AS RISK_SIGNAL_SCORE
FROM NORMALIZED;

SELECT * FROM ANALYTICS_RISK_SIGNALS_NORMALIZED LIMIT 10;


