---HYPOTHESIS 1 — Engagement drop vs rating difference 
CREATE OR REPLACE TABLE HYPOTHESIS_1_TEST AS 
SELECT m.BUSINESS_ID,
 m.YEAR_MONTH, 
m.AVG_RATING, 
COALESCE(c.CHECKINS_COUNT,0) AS CHECKINS_COUNT, ROUND((m.REVIEWS_COUNT*0.6)+(COALESCE(c.CHECKINS_COUNT,0)*0.4),2) AS ENGAGEMENT_SCORE, 
CASE WHEN ENGAGEMENT_SCORE < (SELECT MEDIAN(ENGAGEMENT_SCORE) FROM (SELECT ROUND((REVIEWS_COUNT*0.6)+(CHECKINS_COUNT*0.4),2) AS ENGAGEMENT_SCORE FROM ANALYTICS_RESTAURANT_MONTHLY m2
 JOIN
 ANALYTICS_RESTAURANT_CHECKINS_MONTHLY c2 
ON m2.BUSINESS_ID = c2.BUSINESS_ID 
AND m2.YEAR_MONTH = c2.YEAR_MONTH)) THEN 'ENGAGEMENT_DROP' 
ELSE 'NO_ENGAGEMENT_DROP' END AS ENGAGEMENT_GROUP FROM 
ANALYTICS_RESTAURANT_MONTHLY m 
LEFT JOIN ANALYTICS_RESTAURANT_CHECKINS_MONTHLY c 
ON m.BUSINESS_ID = c.BUSINESS_ID AND m.YEAR_MONTH = c.YEAR_MONTH 
ORDER BY m.BUSINESS_ID, m.YEAR_MONTH; select count(*) 
from HYPOTHESIS_1_TEST

--HYPOTHESIS 2 — Engagement down linked with rating down
CREATE OR REPLACE TABLE HYPOTHESIS_2_TEST AS 
SELECT BUSINESS_ID, YEAR_MONTH, AVG_RATING, RATING_VOLATILITY,
LAG(AVG_RATING,1) OVER (PARTITION BY BUSINESS_ID ORDER BY TO_DATE(YEAR_MONTH||'-01')) AS RATING_LAST_MONTH, 
ROUND(AVG_RATING - RATING_LAST_MONTH,2) AS RATING_CHANGE_1M, RATING_CHANGE_1M < 0 AS RATING_DOWN_FLAG, 
LAG(REVIEWS_COUNT,1) OVER (PARTITION BY BUSINESS_ID ORDER BY TO_DATE(YEAR_MONTH||'-01')) AS REVIEWS_LAST_MONTH,
ROUND(REVIEWS_COUNT - REVIEWS_LAST_MONTH,2) AS REVIEW_CHANGE_1M, REVIEW_CHANGE_1M < 0 AS ENGAGEMENT_DOWN_FLAG 
FROM ANALYTICS_RESTAURANT_MONTHLY O
RDER BY BUSINESS_ID, YEAR_MONTH;

-- HYPOTHESIS 3 — High volatility vs open/closed behavior 
CREATE OR REPLACE 
TABLEHYPOTHESIS_3_TEST AS 
SELECT m.BUSINESS_ID, m.YEAR_MONTH, m.AVG_RATING, m.REVIEWS_COUNT, m.RATING_VOLATILITY, b.OPENED, 
CASE WHEN m.RATING_VOLATILITY > (SELECT MEDIAN(RATING_VOLATILITY) FROM ANALYTICS_RESTAURANT_MONTHLY) THEN 'HIGH_VOLATILITY' ELSE 'LOW_VOLATILITY' END AS VOL_GROUP 
FROM ANALYTICS_RESTAURANT_MONTHLY m 
JOIN STG_YELP_BUSINESS b ON m.BUSINESS_ID = b.BUSINESS_ID ORDER BY m.BUSINESS_ID, m.YEAR_MONTH;

--HYPOTHESIS 4 — Do popular businesses fail less or more? 
CREATE OR REPLACE TABLE HYPOTHESIS_4_TEST AS 
WITH CTE AS 
( SELECT BUSINESS_ID, 
AVG(AVG_RATING) AS AVG_RATING_BUSINESS, 
MAX(REVIEWS_COUNT) AS MAX_MONTHLY_REVIEWS, 
CASE 
   WHEN MAX_MONTHLY_REVIEWS > 50 THEN 'VERY_POPULAR' 
   WHEN MAX_MONTHLY_REVIEWS BETWEEN 20 AND 50 THEN 'MED_POPULAR' 
   ELSE 'LOW_POPULAR' 
END AS POPULARITY_GROUP 
FROM ANALYTICS_RESTAURANT_MONTHLY 
GROUP BY BUSINESS_ID ) 
SELECT c.BUSINESS_ID, c.AVG_RATING_BUSINESS, c.MAX_MONTHLY_REVIEWS, c.POPULARITY_GROUP, b.OPENED 
FROM CTE c 
JOIN STG_YELP_BUSINESS b 
ON c.BUSINESS_ID = b.BUSINESS_ID 
ORDER BY MAX_MONTHLY_REVIEWS DESC;

--HYPOTHESIS 5 — Do elite reviewers impact risky restaurants more? 

CREATE OR REPLACE TABLE HYPOTHESIS_5_ELITE_IMPACT AS 
SELECT r.BUSINESS_ID, r.YEAR_MONTH, r.REVIEWS_COUNT, r.AVG_RATING, r.RATING_VOLATILITY, u.ELITE AS REVIEWER_ELITE, u.REVIEW_COUNT AS REVIEWER_TOTAL_REVIEWS, 
DATEDIFF('year', u.YELPING_SINCE, CURRENT_DATE()) AS REVIEWER_AGE_YEARS, 
CASE 
     WHEN REVIEWER_AGE_YEARS > 5 THEN 'OLD_USER' 
     ELSE 'NEW_USER'
END AS REVIEWER_GROUP 
FROM ANALYTICS_RESTAURANT_MONTHLY r 
JOIN STG_YELP_REVIEWS r2 
ON r.BUSINESS_ID = r2.BUSINESS_ID AND r.YEAR_MONTH = TO_CHAR(r2.REVIEW_DATE,'YYYY-MM') 
JOIN STG_YELP_USER u ON r2.USER_ID = u.USER_ID ORDER BY r.BUSINESS_ID, r.YEAR_MONTH